import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "@/context/ReactQueryProvider"
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <ReactQueryProvider>      
        <body className={`${poppins.className}`}>
        {children}
        </body>
        <Toaster position="top-right"/>
        </ReactQueryProvider>

    </html>
  );
}
